name: Gerard Tonti - New Paintings
favicon: null
layout_spectrum: 0.28549
typography_spectrum: 0.3388935034163296
title: "Gerard Tonti - What's New"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1dfec'
    - '#121212'
    - '#483429'
    - '#7e6254'
    - '#9aa8b4'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
