name: Gerard Tonti - New Paintings
favicon: null
layout_spectrum: 0.90401
typography_spectrum: 0.3388935034163296
title: Gerard Tonti - New Paintings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a57044'
    - '#89461b'
    - '#c79c6f'
    - '#e3be91'
    - '#220c0a'
  brandStrength: 0.625
  lightness: 0.18912454298697412
  saturation: 0.9045532955788076
  rhythmicContrast: 0.75
purpose: []
