name: Gerard Tonti
favicon: null
layout_spectrum: 0.72308
typography_spectrum: 0.3388935034163296
title: "What's New"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1dfec'
    - '#121212'
    - '#483429'
    - '#7e6254'
    - '#9aa8b4'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
